import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, shareReplay } from 'rxjs';

/** One `@Input()` on a shipped component, as extracted by
 * `scripts/generate-design-system-manifest.mjs`. */
export interface ManifestInput {
  name: string;
  type: string;
  values: string[] | null;
  default: string | null;
  optional: boolean;
}

/** One shipped component entry in `docs/brand/design-system.manifest.json` /
 * `/design-system/manifest.json`. */
export interface ManifestComponent {
  name: string;
  slug: string;
  className: string | null;
  sourcePath: string;
  previewPath: string | null;
  inputs: ManifestInput[];
  variants: string[] | null;
  viewports: string[];
}

export interface DesignSystemManifest {
  generatedBy: string;
  generatedFrom: string;
  note: string;
  componentCount: number;
  components: ManifestComponent[];
}

/** Tier assignment for one of the 67 PrimeNG components with no dedicated INOVIXUX build
 * (`docs/brand/24-primeng-component-audit-ino-31.md` §2 Matrix B, finding F-2). */
export interface DispositionItem {
  component: string;
  group: string;
  tier: 'Tier-1' | 'Tier-2' | 'Tier-3';
  status: string;
  sourceNote: string;
}

export interface ComponentDisposition {
  generatedFrom: string;
  note: string;
  items: DispositionItem[];
}

/** Extracted "Accessibility contract" / "Deliberate omissions" markdown for one shipped
 * component, keyed by slug. `docPath`/`a11y`/`notes` are all null for components with no
 * narrative doc (5 marketing-only components, plus any not-yet-documented new component). */
export interface ComponentDocExtract {
  name: string;
  docPath: string | null;
  a11y: string | null;
  notes: string | null;
}

export interface ComponentDocsExtract {
  generatedBy: string;
  generatedFrom: string;
  note: string;
  components: Record<string, ComponentDocExtract>;
}

/**
 * Fetches the three generated, runtime-published `/design-system/*.json` blobs
 * (`web/public/design-system/`) that the `/docs/components` portal (INO-317) renders from.
 * All three are static JSON served as-is by Angular's `public/` asset glob
 * (`web/angular.json`), generated by `scripts/generate-*.mjs` — never hand-authored — so this
 * service is a thin, cached (`shareReplay(1)`) HTTP wrapper shared by the index and detail pages
 * rather than each page issuing its own duplicate GETs.
 */
@Injectable({ providedIn: 'root' })
export class ComponentDocsDataService {
  private readonly http = inject(HttpClient);

  private readonly manifest$ = this.http
    .get<DesignSystemManifest>('/design-system/manifest.json')
    .pipe(shareReplay(1));

  private readonly disposition$ = this.http
    .get<ComponentDisposition>('/design-system/component-disposition.json')
    .pipe(shareReplay(1));

  private readonly docsExtract$ = this.http
    .get<ComponentDocsExtract>('/design-system/component-docs-extract.json')
    .pipe(shareReplay(1));

  getManifest(): Observable<DesignSystemManifest> {
    return this.manifest$;
  }

  getDisposition(): Observable<ComponentDisposition> {
    return this.disposition$;
  }

  getDocsExtract(): Observable<ComponentDocsExtract> {
    return this.docsExtract$;
  }
}
